### ISSUE TITLE
Working on Home page creation

### ISSUE THREAD

**Issue by enguyen93** [enguyen93/EvergardenServices#8]

**Comment by solr-c** [comment]
![esg320](https://user-images.githubusercontent.com/9100640/51594823-f08c7d00-1eba-11e9-91e1-4862d81d42fe.png)
![esg768](https://user-images.githubusercontent.com/9100640/51594824-f08c7d00-1eba-11e9-8746-278c3fda55d7.png)
![esg1920](https://user-images.githubusercontent.com/9100640/51594826-f08c7d00-1eba-11e9-94b4-44ef36913884.png)
Made prototype homepage mobile friendly, if needed. Just a simple mockup for the night.

**Comment by solr-c** [comment]
Finished home, login and sign up, last is dashboard
